/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorSettingsRouteImport } from './routes/vendor.settings'
import { Route as VendorReportsRouteImport } from './routes/vendor.reports'
import { Route as VendorProductsRouteImport } from './routes/vendor.products'
import { Route as VendorOrdersRouteImport } from './routes/vendor.orders'
import { Route as VendorNotificationsRouteImport } from './routes/vendor.notifications'
import { Route as VendorDashboardRouteImport } from './routes/vendor.dashboard'
import { Route as VendorCustomersRouteImport } from './routes/vendor.customers'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorSettingsRoute = VendorSettingsRouteImport.update({
  id: '/vendor/settings',
  path: '/vendor/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorReportsRoute = VendorReportsRouteImport.update({
  id: '/vendor/reports',
  path: '/vendor/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorProductsRoute = VendorProductsRouteImport.update({
  id: '/vendor/products',
  path: '/vendor/products',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorOrdersRoute = VendorOrdersRouteImport.update({
  id: '/vendor/orders',
  path: '/vendor/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorNotificationsRoute = VendorNotificationsRouteImport.update({
  id: '/vendor/notifications',
  path: '/vendor/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorDashboardRoute = VendorDashboardRouteImport.update({
  id: '/vendor/dashboard',
  path: '/vendor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorCustomersRoute = VendorCustomersRouteImport.update({
  id: '/vendor/customers',
  path: '/vendor/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/dashboard': typeof DashboardRoute
  '/menu': typeof MenuRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/vendor/customers': typeof VendorCustomersRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/notifications': typeof VendorNotificationsRoute
  '/vendor/orders': typeof VendorOrdersRoute
  '/vendor/products': typeof VendorProductsRoute
  '/vendor/reports': typeof VendorReportsRoute
  '/vendor/settings': typeof VendorSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/dashboard': typeof DashboardRoute
  '/menu': typeof MenuRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/vendor/customers': typeof VendorCustomersRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/notifications': typeof VendorNotificationsRoute
  '/vendor/orders': typeof VendorOrdersRoute
  '/vendor/products': typeof VendorProductsRoute
  '/vendor/reports': typeof VendorReportsRoute
  '/vendor/settings': typeof VendorSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/dashboard': typeof DashboardRoute
  '/menu': typeof MenuRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/vendor/customers': typeof VendorCustomersRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/notifications': typeof VendorNotificationsRoute
  '/vendor/orders': typeof VendorOrdersRoute
  '/vendor/products': typeof VendorProductsRoute
  '/vendor/reports': typeof VendorReportsRoute
  '/vendor/settings': typeof VendorSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/dashboard'
    | '/menu'
    | '/notifications'
    | '/orders'
    | '/profile'
    | '/settings'
    | '/signup'
    | '/admin/orders'
    | '/vendor/customers'
    | '/vendor/dashboard'
    | '/vendor/notifications'
    | '/vendor/orders'
    | '/vendor/products'
    | '/vendor/reports'
    | '/vendor/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/dashboard'
    | '/menu'
    | '/notifications'
    | '/orders'
    | '/profile'
    | '/settings'
    | '/signup'
    | '/admin/orders'
    | '/vendor/customers'
    | '/vendor/dashboard'
    | '/vendor/notifications'
    | '/vendor/orders'
    | '/vendor/products'
    | '/vendor/reports'
    | '/vendor/settings'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/dashboard'
    | '/menu'
    | '/notifications'
    | '/orders'
    | '/profile'
    | '/settings'
    | '/signup'
    | '/admin/orders'
    | '/vendor/customers'
    | '/vendor/dashboard'
    | '/vendor/notifications'
    | '/vendor/orders'
    | '/vendor/products'
    | '/vendor/reports'
    | '/vendor/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  DashboardRoute: typeof DashboardRoute
  MenuRoute: typeof MenuRoute
  NotificationsRoute: typeof NotificationsRoute
  OrdersRoute: typeof OrdersRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  VendorCustomersRoute: typeof VendorCustomersRoute
  VendorDashboardRoute: typeof VendorDashboardRoute
  VendorNotificationsRoute: typeof VendorNotificationsRoute
  VendorOrdersRoute: typeof VendorOrdersRoute
  VendorProductsRoute: typeof VendorProductsRoute
  VendorReportsRoute: typeof VendorReportsRoute
  VendorSettingsRoute: typeof VendorSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/settings': {
      id: '/vendor/settings'
      path: '/vendor/settings'
      fullPath: '/vendor/settings'
      preLoaderRoute: typeof VendorSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/reports': {
      id: '/vendor/reports'
      path: '/vendor/reports'
      fullPath: '/vendor/reports'
      preLoaderRoute: typeof VendorReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/products': {
      id: '/vendor/products'
      path: '/vendor/products'
      fullPath: '/vendor/products'
      preLoaderRoute: typeof VendorProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/orders': {
      id: '/vendor/orders'
      path: '/vendor/orders'
      fullPath: '/vendor/orders'
      preLoaderRoute: typeof VendorOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/notifications': {
      id: '/vendor/notifications'
      path: '/vendor/notifications'
      fullPath: '/vendor/notifications'
      preLoaderRoute: typeof VendorNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/dashboard': {
      id: '/vendor/dashboard'
      path: '/vendor/dashboard'
      fullPath: '/vendor/dashboard'
      preLoaderRoute: typeof VendorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/customers': {
      id: '/vendor/customers'
      path: '/vendor/customers'
      fullPath: '/vendor/customers'
      preLoaderRoute: typeof VendorCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  DashboardRoute: DashboardRoute,
  MenuRoute: MenuRoute,
  NotificationsRoute: NotificationsRoute,
  OrdersRoute: OrdersRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  VendorCustomersRoute: VendorCustomersRoute,
  VendorDashboardRoute: VendorDashboardRoute,
  VendorNotificationsRoute: VendorNotificationsRoute,
  VendorOrdersRoute: VendorOrdersRoute,
  VendorProductsRoute: VendorProductsRoute,
  VendorReportsRoute: VendorReportsRoute,
  VendorSettingsRoute: VendorSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
